version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 512
virtualmachines:
- name: nixagent1
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-1
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-standard-4
- name: nixagent2
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-1
- name: winagent
  image: kmo-instruqt/windows-iis-test
  machine_type: n1-standard-2
