version: "2"
virtualmachines:
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe201-lab-1-1
  machine_type: n1-standard-1
- name: puppet
  image: kmo-instruqt/puppet-pe201-lab-1-1
  machine_type: n1-highcpu-32
