version: "2"
virtualmachines:
- name: nixagent
  image: kmo-instruqt/linux-node-no-agent
  shell: /bin/bash
  machine_type: n1-standard-1
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-standard-4
